${( _self = this ),''}
<div class="klear-gallery">
{{if this.data.currentPage == "index"}}

    <div>
        <div class="topMenu">
            <div>
                <a class="action ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only newGallery"
                   title="<?= $this->translate("Nueva galería"); ?>">
                    <span class="ui-button-text">
                        <span title="<?= $this->translate("Nueva galería"); ?>" class="ui-silk inline ui-silk-add"></span>
                        <?= $this->translate("Nueva galería"); ?>
                    </span>
                </a>
            </div>
        </div>
        <br style="clear:both;"/>
        <table class="kMatrix">
          <caption class="ui-state-active ui-priority-primary">
                <?= $this->translate("Listado de Galerías"); ?>
                <span class="extraCaptionInfo"> <?= $this->translate("Total"); ?>:
                <strong>${this.data.galleries.length}</strong> <?= $this->translate("Registros"); ?> </span>
          </caption>
          <tbody>
          <tr class="ui-widget-content">
            <th class="ui-widget-header" data-field="pk">
              <span class="title"><?= $this->translate("Galería"); ?></span>
            </th>
            <th class="ui-widget-header" data-field="name">
              <span class="title"><?= $this->translate("Nº Elementos"); ?></span>
            </th>
            <th class="ui-widget-header" data-field="name">
              <span class="title"><?= $this->translate("Opciones"); ?></span>
            </th>
          {{each(idx,gallery) this.data.galleries}}
          <tr class="ui-widget-content">
            <td class="ui-widget-content default">
                <a href="${baseUrl}&section=gallery&action=load&pk=${gallery.pk}">${gallery.name}</a>
            </td>
            <td class="ui-widget-content">
                ${gallery.recordCount}
            </td>
            <td class="ui-widget-content">
                <a href="${baseUrl}&section=sizes&action=load&pk=${gallery.pk}" title="Gestionar tamaños">
                    <span class="ui-silk inline ui-silk-cog"></span>
                </a>
                <a href="${baseUrl}&section=gallery&action=edit&pk=${gallery.pk}" class="editGallery" title="Editar Galería">
                    <span class="ui-silk inline ui-silk-pencil"></span>
                </a>
                <a rel="${baseUrl}&section=gallery&action=remove&pk=${gallery.pk}"  title="Eliminar" class="delete">
                    <span class="ui-silk inline ui-silk-bin"></span>
                </a>
            </td>
          </tr>
          {{/each}}
          </tbody>
        </table>
    </div>

    <div style="display:none;" class="ui-tabs-panel ui-widget-content ui-corner-bottom">
        <a class="action return ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" title="Volver"
           href="${baseUrl}&section=index">
            <span class="ui-button-text">
                <span title="Volver" class="ui-silk inline ui-silk-arrow-left"></span> <?= $this->translate("Volver");?>
            </span>
        </a>

        <form method="POST" class="klearMatrix_form" action="${_self.data.baseUrl}&section=gallery&action=save">
            <fieldset class="ui-widget-content ui-corner-all">
                <legend class="ui-widget-header ui-corner-all"><?php echo $this->translate("Galería"); ?></legend>

                {{if this.data.galleryStructure.isMultilang == true}}

                    <div class="container ui-widget-content ui-corner-all">
                        <label rel="name" for="name48110">${this.data.galleryStructure.field}</label>
                        <dl class="multiLanguage">
                            {{each(idx,language) this.data.galleryStructure.availableLangs}}
                                <dt class="selected">
                                    <label class="lang">[${language}]</label>
                                </dt>
                                <dd class="selected">
                                    <input type="text" name="${_self.data.galleryStructure.field}${language}" value="" class="ui-widget ui-state-default ui-corner-all" style="width: 142px; ">
                                </dd>
                            {{/each}}
                        </dl>
                    </div>

                {{else}}

                    <div class="container ui-widget-content ui-corner-all">
                        <label>${this.data.galleryStructure.field}</label>
                        <input type="text" value="${this.data.galleryStructure.field}" name="" class="ui-widget ui-state-default ui-corner-all">
                    </div>

                {{/if}}

            </fieldset>
            <div class="generalOptionsToolbar ui-widget-content ui-corner-all">
              <a title="<?php echo $this->translate("Guardar");?>"
                 class="action submit ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" role="button"
              >
                <span class="ui-button-text">
                  <span class="ui-silk inline ui-silk-bullet-disk"></span>
                  <?php echo $this->translate("Guardar");?>
                </span>
              </a>
            </div>
            <input type="hidden" name="pk" value="" />
        </form>
    </div>
{{/if}}



{{if this.data.currentPage == "gallery" && this.data.currentAction == "load"}}
    <div class="topMenu">
        <a class="action ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" title="<?= $this->translate("volver");?>" href="${baseUrl}">
            <span class="ui-button-text">
                <span title="<?= $this->translate("Volver"); ?>" class="ui-silk inline ui-silk-arrow-left"></span>
                <?= $this->translate("Volver"); ?>
            </span>
        </a>

        <div class="right">
            <a class="action ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only newImg"
               title="<?= $this->translate("Nueva imagen"); ?>">
                <span class="ui-button-text">
                    <span title="<?= $this->translate("Nueva imagen"); ?>" class="ui-silk inline ui-silk-add"></span>
                    <?= $this->translate("Añadir"); ?>
                </span>
            </a>
            <a style="display:none;" class="action ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only newImg"
               title="<?= $this->translate("Volver"); ?>">
                <span class="ui-button-text">
                    <span title="<?= $this->translate("Volver"); ?>" class="ui-silk inline ui-silk-arrow-undo"></span>
                    <?= $this->translate("Cancelar"); ?>
                </span>
            </a>
         </div>
    </div>
    <br style="clear:both;"/>
    <div class="galleryContent">
        <ul class="pictureList">
        {{each(idx,picture) this.data.pictures}}
            <li>
                <a href="${baseUrl}&section=picture&action=load&pk=${picture.pk}&page=${_self.data.paginator.current}">
                    <img rel="${publicImgRoute}?pk=${picture.pk}&size=100" src="${baseUrl}&section=picture&action=load&pk=${picture.pk}&preview=true&size=100" />
                    <br />
                    ${picture.name}
                </a>
            </li>
        {{/each}}
        </ul>
        <div style="display:none;" class="uploader" style="border: 4px dashed #DDDDDD">
            <div class="drag-drop-inside qq-upload-drop-area-active">
                <p class="drag-drop-info"><?= $this->translate("Arrastra el archivo aquí"); ?></p>
                <p>o</p>
                <p class="drag-drop-buttons">
                    <input type="button" class="button" value="<?= $this->translate("Elegir archivo"); ?>"
                    id="plupload-browse-button" style="position: relative; z-index: 0;" />
                </p>
            </div>
        </div>

        <div class="paginator ui-widget-content ui-corner-all">
            <a href="${this.data.baseUrl}&section=gallery&action=load&pk=${this.data.galleryId}&page=${this.data.paginator.first}" class="ui-state-default">«</a>
            <a href="${this.data.baseUrl}&section=gallery&action=load&pk=${this.data.galleryId}&page={{if ( this.data.paginator.previous)}}${ this.data.paginator.previous}{{else}}${ this.data.paginator.current}{{/if}}" class="ui-state-default">‹</a>

            {{each(idx,_curPage) this.data.paginator.pagesInRange}}
                <a href="${_self.data.baseUrl}&section=gallery&action=load&pk=${_self.data.galleryId}&page=${_curPage}" class="{{if (_curPage== _self.data.paginator.current)}}ui-state-active{{else}}ui-state-default{{/if}}" data-page="${_curPage}">${_curPage}</a>
            {{/each}}

            <a class="ui-state-default" href="${this.data.baseUrl}&section=gallery&action=load&pk=${this.data.galleryId}&page={{if (this.data.paginator.next)}}${this.data.paginator.next}{{else}}${ this.data.paginator.lastPageInRange}{{/if}}">›</a>
            <a class="ui-state-default" href="${this.data.baseUrl}&section=gallery&action=load&pk=${this.data.galleryId}&page=${ this.data.paginator.lastPageInRange}">»</a>
        </div>
    </div>

{{/if}}

{{if this.data.currentPage == "picture"}}
    <div class="topMenu">
        <a class="return action ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" title="<?= $this->translate("Volver");?>"
            href="${baseUrl}&section=gallery&action=load&pk=${this.data.picture[this.data.fieldToParentTable]}&page=${this.data.page}">
            <span class="ui-button-text">
                <span title="<?= $this->translate("Volver"); ?>" class="ui-silk inline ui-silk-arrow-left"></span> <?= $this->translate("Volver"); ?>
            </span>
        </a>

        <div class="right">
            <a class="delete action ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" title="<?= $this->translate("Eliminar");?>"
                rel="${baseUrl}&section=picture&action=remove&pk=${this.data.picture.pk}">
                <span class="ui-button-text">
                    <span title="<?= $this->translate("Eliminar");?>" class="ui-silk inline ui-silk-camera-delete"></span> <?= $this->translate("Eliminar");?>
                </span>
            </a>
            <a class="edit init action ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" title="<?= $this->translate("Modo edición");?>">
                <span class="ui-button-text">
                    <span class="ui-silk inline ui-silk-pencil"></span>
                    <?= $this->translate("Editar");?>
                </span>
            </a>
            <a style="display:none;" class="edit cancel action ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only"
               title="<?= $this->translate("Cancelar modo edición");?>">
                <span class="ui-button-text">
                    <span title="<?= $this->translate("Volver");?>" class="ui-silk inline  ui-silk-arrow-undo"></span>
                    <?= $this->translate("Cancelar");?>
                </span>
            </a>
            <a style="display:none;" class="save action ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only"
               title="<?= $this->translate("Guardar");?>">
                <span class="ui-button-text">
                    <span title="Volver" class="ui-silk inline ui-silk-bullet-disk"></span>
                    <?= $this->translate("Guardar");?>
                </span>
            </a>
        </div>
    </div>

    <div class="pictureDetail klearMatrix_form">
        <fieldset class="ui-widget-content ui-corner-all">
            <legend class="ui-widget-header ui-corner-all">${this.data.picture.title}&nbsp;</legend>
            <div class="selectableImgWrapper">
                <img data-baseUrl="${this.data.publicImgBase}"
                     data-uri="${this.data.publicImgUri}"
                     data-extension="${this.data.picture.extension}"
                     data-pk="${this.data.picture.pk}"
                     data-alt="${this.data.picture.title}"
                     class="selectable"
                     src="${baseUrl}&section=picture&action=load&pk=${this.data.picture.pk}&preview=true" style="max-width:370px;" />
            </div>
            <div>
                <p class="sizeSelector" style="display:none;float:left;">
                    <select name="size" class="sizeSelector">
                        <option value=""><?= $this->translate("Tamaño original");?></option>
                        {{each(idx, row) this.data.picture.availableDimensions}}
                            <option value="${row.pk}">
                                ${row.width.value}x${row.height.value}
                                [${row.policy.value}]
                            </option>
                        {{/each}}
                    </select>
                </p>
                <div class="right insert" style="display:none;">
                    <a class="insert action ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" title="<?= $this->translate("Insertar");?>">
                        <span class="ui-button-text">
                            <span title="<?= $this->translate("Insertar"); ?>" class="ui-silk inline ui-silk-image-add"></span> <?= $this->translate("Insertar"); ?>
                        </span>
                    </a>
                </div>
            </div>
            <br style="clear:both;"/>
            <div>
                <div class="ui-widget-header photoTitle">
                    <strong><?= $this->translate("Texto alternativo");?> [${this.data.language}]:</strong>
                    <form method="POST" style="display:inline;"
                     action="${baseUrl}&section=picture&action=update&pk=${this.data.picture.pk}">
                        <span>${this.data.picture.title}</span>
                        <input size="17" style="display:none;" type="text" name="${this.data.picture.titleFieldName}" value="${this.data.picture.title}" />
                    </form>
                </div>
                <div class="container ui-widget-header ui-state-default metadata">
                    <p>
                        <?= $this->translate("Nombre de archivo");?>: <span>${this.data.picture.fileName}</span>
                    </p>
                    <p>
                        Detalles de la imagen:
                        <span>
                            ${this.data.picture.size} kb <strong>-</strong>
                            ${this.data.picture.dimensions.width}x${this.data.picture.dimensions.height}px <strong>-</strong>
                            ${this.data.picture.mimetype}
                        </span>
                    </p>
                </div>
            </div>
        </fieldset>
    </div>
{{/if}}

{{if this.data.currentPage == "sizes" && this.data.currentAction == "load" }}
    <div class="topMenu">
        <a class="action ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only return" title="Volver"
           href="${baseUrl}&section=index&action=load&pk=${this.data.sizes[this.data.fieldToParentTable]}">
            <span class="ui-button-text">
                <span title="Volver" class="ui-silk inline ui-silk-arrow-left return"></span> <?= $this->translate("Volver");?>
            </span>
        </a>
        <div class="right">
            <a class="action ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only"
               title="<?= $this->translate("Añadir"); ?>" href="${_self.data.baseUrl}&section=sizes&action=new&parentPk=${_self.data.parentPk}">
                <span class="ui-button-text">
                    <span title="<?= $this->translate("Añadir"); ?>" class="ui-silk inline ui-silk-add"></span>
                    <?= $this->translate("Añadir"); ?>
                </span>
            </a>
        </div>
        <br style="clear:both;" />
    </div>
    <div style="margin-top:20px;">
        <table class="kMatrix">
          <caption class="ui-state-active ui-priority-primary">
            <?= $this->translate("Tamaños de imagen");?>  <span class="extraCaptionInfo">
            <?= $this->translate("Total");?>:<strong>${this.data.sizes.length}</strong> <?= $this->translate("Registros");?> </span>
          </caption>
          <tbody>
          <tr class="ui-widget-content">
            <th class="ui-widget-header" data-field="pk">
              <span class="title"><?= $this->translate("Ancho"); ?></span>
            </th>
            <th class="ui-widget-header" data-field="name">
              <span class="title"><?= $this->translate("Alto"); ?></span>
            </th>
            <th class="ui-widget-header" data-field="name">
              <span class="title"><?= $this->translate("Política"); ?></span>
            </th>
            <th class="ui-widget-header" data-field="name">
              <span class="title"><?= $this->translate("Opciones");?></span>
            </th>
          </tr>
          {{each(idx,row) this.data.sizes}}
          <tr class="ui-widget-content">
            <td>
                ${row.width.value}
            </td>
            <td>
                ${row.height.value}
            </td>
            <td>
                ${row.policy.value}
            </td>
            <td>
                <a title="<?= $this->translate("Editar");?>" href="${_self.data.baseUrl}&section=sizes&action=edit&parentPk=${_self.data.parentPk}&pk=${row.pk}"
                   class="option screen default ui-state-nojump">
                    <span class="ui-silk inline ui-silk-pencil"></span>
                </a>
                <a title="<?= $this->translate("Delete");?>" data-dialog="pagEstaticasDel_dialog" class="option ui-state-nojump delete"
                   rel="${_self.data.baseUrl}&section=sizes&action=delete&parentPk=${_self.data.parentPk}&pk=${row.pk}"
                >
                    <span class="ui-silk inline ui-silk-bin"></span>
                </a>
            </td>
          </tr>
          {{/each}}
          </tbody>
        </table>
    </div>
{{/if}}

{{if this.data.currentPage == "sizes" && (this.data.currentAction == "edit" || this.data.currentAction == "new") }}
<div class="ui-tabs-panel ui-widget-content ui-corner-bottom">
    <a class="action return ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" title="Volver"
       href="${baseUrl}&section=sizes&action=load&pk=${this.data.parentPk}">
        <span class="ui-button-text">
            <span title="Volver" class="ui-silk inline ui-silk-arrow-left"></span> <?= $this->translate("Volver");?>
        </span>
    </a>

    <form method="POST" class="klearMatrix_form" action="${_self.data.baseUrl}&section=sizes&action=save&parentPk=${this.data.parentPk}&pk=${this.data.sizes[0].pk}">
        <fieldset class="ui-widget-content ui-corner-all">
            <legend class="ui-widget-header ui-corner-all"><?php echo $this->translate("Editar"); ?></legend>

            <div class="container ui-widget-content ui-corner-all">
                <label><?= $this->translate("Ancho"); ?></label>
                <input type="text" value="${this.data.sizes[0].width.value}" name="${this.data.sizes[0].width.fieldName}" class="ui-widget ui-state-default ui-corner-all">
            </div>
            <div class="container ui-widget-content ui-corner-all">
                <label><?= $this->translate("Alto"); ?></label>
                <input type="text" value="${this.data.sizes[0].height.value}" name="${this.data.sizes[0].height.fieldName}" class="ui-widget ui-state-default ui-corner-all">
            </div>
            <div class="container ui-widget-content ui-corner-all">
               <label><?= $this->translate("Política"); ?></label>
               <select name="${this.data.sizes[0].policy.fieldName}">
                   <option value="exact"><?php echo $this->translate("exact"); ?></option>
                   <option value="crop"><?php echo $this->translate("crop"); ?></option>
                   <option value="exactWidth" selected><?php echo $this->translate("exactWidth"); ?></option>
                   <option value="exactHeight"><?php echo $this->translate("exactHeight"); ?></option>
               </select>
            </div>
        </fieldset>
        <div class="generalOptionsToolbar ui-widget-content ui-corner-all">
          <a title="<?php echo $this->translate("Guardar");?>"
             class="action submit ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" role="button"
          >
            <span class="ui-button-text">
              <span class="ui-silk inline ui-silk-bullet-disk"></span>
              <?php echo $this->translate("Guardar");?>
            </span>
          </a>
        </div>
        <input type="hidden" name="pk" value="${this.data.sizes[0].pk}" />
    </form>
</div>
{{/if}}


</div>